// Mocks generated by Mockito 5.4.6 from annotations
// in universo_rick_v2/test/features/characters/presentation/stores/character_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:universo_rick_v2/features/characters/domain/entities/character_entity.dart'
    as _i5;
import 'package:universo_rick_v2/features/characters/domain/repositories/character_repository.dart'
    as _i2;
import 'package:universo_rick_v2/features/characters/domain/usecases/get_all_characters.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeICharacterRepository_0 extends _i1.SmartFake
    implements _i2.ICharacterRepository {
  _FakeICharacterRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllCharacters].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCharacters extends _i1.Mock implements _i3.GetAllCharacters {
  MockGetAllCharacters() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ICharacterRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeICharacterRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ICharacterRepository);

  @override
  _i4.Future<List<_i5.CharacterEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.CharacterEntity>>.value(
              <_i5.CharacterEntity>[],
            ),
          )
          as _i4.Future<List<_i5.CharacterEntity>>);
}
